from PyQt6.Qsci import QsciLexerAsm, QsciLexerAVS, QsciLexerBash, QsciLexerBatch, QsciLexerCMake, QsciLexerCoffeeScript, \
    QsciLexerCPP, QsciLexerCSharp, QsciLexerCSS, QsciLexerD, QsciLexerDiff, QsciLexerFortran, \
    QsciLexerFortran77, QsciLexerHex, QsciLexerHTML, QsciLexerIDL, QsciLexerJava, \
    QsciLexerJavaScript, QsciLexerJSON, QsciLexerLua, QsciLexerMakefile, QsciLexerMarkdown, QsciLexerMASM, \
    QsciLexerOctave, QsciLexerPascal, QsciLexerPerl, QsciLexerPO, QsciLexerPostScript, \
    QsciLexerPOV, QsciLexerProperties, QsciLexerPython, QsciLexerRuby, QsciLexerSpice, QsciLexerSQL, QsciLexerSRec, \
    QsciLexerTCL, QsciLexerTekHex, QsciLexerTeX, QsciLexerVerilog, QsciLexerVHDL, QsciLexerXML, QsciLexerYAML

LEXER_MAP = {
    ".asm": QsciLexerAsm,
    ".s": QsciLexerAsm,
    ".a51": QsciLexerAsm,
    ".avs": QsciLexerAVS,
    ".sh": QsciLexerBash,
    ".bat": QsciLexerBatch,
    ".cmd": QsciLexerBatch,
    ".cmake": QsciLexerCMake,
    "CMakeLists.txt": QsciLexerCMake,
    ".coffee": QsciLexerCoffeeScript,
    ".cpp": QsciLexerCPP,
    ".cxx": QsciLexerCPP,
    ".cc": QsciLexerCPP,
    ".h": QsciLexerCPP,
    ".hpp": QsciLexerCPP,
    ".hxx": QsciLexerCPP,
    ".hh": QsciLexerCPP,
    ".c": QsciLexerCPP,
    ".cs": QsciLexerCSharp,
    ".css": QsciLexerCSS,
    ".d": QsciLexerD,
    ".diff": QsciLexerDiff,
    ".patch": QsciLexerDiff,
    ".f90": QsciLexerFortran,
    ".f95": QsciLexerFortran,
    ".f03": QsciLexerFortran,
    ".f08": QsciLexerFortran,
    ".for": QsciLexerFortran,
    ".f": QsciLexerFortran,
    ".f77": QsciLexerFortran77,
    ".hex": QsciLexerHex,
    ".html": QsciLexerHTML,
    ".htm": QsciLexerHTML,
    ".xhtml": QsciLexerHTML,
    ".idl": QsciLexerIDL,
    ".java": QsciLexerJava,
    ".js": QsciLexerJavaScript,
    ".json": QsciLexerJSON,
    ".lua": QsciLexerLua,
    "Makefile": QsciLexerMakefile,
    "makefile": QsciLexerMakefile,
    ".mak": QsciLexerMakefile,
    ".mk": QsciLexerMakefile,
    ".md": QsciLexerMarkdown,
    ".markdown": QsciLexerMarkdown,
    ".a": QsciLexerMASM,
    ".m": QsciLexerOctave,
    ".pas": QsciLexerPascal,
    ".pp": QsciLexerPascal,
    ".inc": QsciLexerPascal,
    ".pl": QsciLexerPerl,
    ".pm": QsciLexerPerl,
    ".t": QsciLexerPerl,
    ".po": QsciLexerPO,
    ".ps": QsciLexerPostScript,
    ".eps": QsciLexerPostScript,
    ".pov": QsciLexerPOV,
    ".properties": QsciLexerProperties,
    ".ini": QsciLexerProperties,
    ".py": QsciLexerPython,
    ".rb": QsciLexerRuby,
    ".sp": QsciLexerSpice,
    ".cir": QsciLexerSpice,
    ".sql": QsciLexerSQL,
    ".srec": QsciLexerSRec,
    ".s19": QsciLexerSRec,
    ".mot": QsciLexerSRec,
    ".tcl": QsciLexerTCL,
    ".tek": QsciLexerTekHex,
    ".tex": QsciLexerTeX,
    ".sty": QsciLexerTeX,
    ".cls": QsciLexerTeX,
    ".v": QsciLexerVerilog,
    ".vh": QsciLexerVerilog,
    ".vhd": QsciLexerVHDL,
    ".vhdl": QsciLexerVHDL,
    ".xml": QsciLexerXML,
    ".xsl": QsciLexerXML,
    ".xsd": QsciLexerXML,
    ".xslt": QsciLexerXML,
    ".wsdl": QsciLexerXML,
    ".yaml": QsciLexerYAML,
    ".yml": QsciLexerYAML
}
